# Generated by Django 4.1.5 on 2023-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('muscle_group', models.CharField(max_length=100)),
                ('exercise', models.TextField(max_length=100)),
                ('level', models.TextField(max_length=100)),
                ('u_l_c', models.TextField(max_length=100)),
                ('p_p', models.TextField(max_length=100)),
                ('modality', models.TextField(max_length=100)),
                ('joint', models.TextField(max_length=100)),
            ],
        ),
    ]
